name: DEPLOY
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        run: |
          eval "$(ssh-agent -s)" && ssh-add -t 60 - <<< "${{secrets.DEPLOY}}"
          git clone git@github.com:shiviraj/counterBuild.git .

      - name: Login to Heroku Container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku
        run: heroku container:push web --app ${{secrets.HEROKU_APP_NAME}}
